LANGUAGES = {
    "English": {
        "app_title": "EcoMeter for Schools",
        "app_header": "Welcome to EcoMeter for Schools!",
        "sidebar_title": "Navigation",
        "language_select": "Select Language",
        "data_entry_page": "Data Entry",
        "dashboard_page": "Dashboard",
        "leaderboard_page": "Leaderboard",
        "admin_page": "Admin",
        "activity_type": "Activity Type",
        "electricity": "Electricity (kWh)",
        "paper": "Paper (sheets)",
        "plastic": "Plastic (kg)",
        "food_waste": "Food/Waste (kg)",
        "transport": "Transport (km)",
        "quantity": "Quantity",
        "submit": "Submit",
        "success_message": "Data submitted successfully!",
        "dashboard_title": "Carbon Footprint Dashboard",
        "total_emissions": "Total CO₂ Emissions",
        "emissions_by_activity": "Emissions by Activity",
        "emissions_by_school": "Emissions by School",
        "leaderboard_title": "Leaderboard",
        "rank": "Rank",
        "school": "School",
        "co2_emissions": "CO₂ Emissions (kg)",
        "admin_title": "Admin Panel",
        "verify_data": "Verify Data Entries",
        "manage_users": "Manage Users",
        "download_data": "Download Data",
        "clear_entries": "Clear Entries",
        "add_school": "Add School",
        "remove_school": "Remove School",
        "school_name": "School Name",
        "add": "Add",
        "remove": "Remove",
        "clear_entries_confirmation": "Are you sure you want to clear all entries? This action cannot be undone.",
        "entries_cleared": "All entries have been cleared.",
        "school_added": "School added successfully!",
        "school_removed": "School removed successfully!",
        "how_to_toggle_themes": "How to toggle themes:",
        "theme_instructions_1": "Click the settings menu (three dots) in the top right corner.",
        "theme_instructions_2": "Select 'Settings'.",
        "theme_instructions_3": "Choose your desired theme from the 'Theme' dropdown.",
        "how_to_update_language": "How to update language text labels:",
        "language_instructions_1": "Open the languages.py file.",
        "language_instructions_2": "Locate the LANGUAGES dictionary.",
        "language_instructions_3": "Update the text for the desired language (e.g., LANGUAGES['English']['app_title'] = 'New Title').",
        "dashboard_suggestions": "Dashboard Suggestions",
        "suggestion_1": "- A time-series chart to show emissions over time.",
        "suggestion_2": "- A 'Top Contributors' section to highlight the activities that contribute the most to the carbon footprint.",
        "suggestion_3": "- A 'Recommendations' section to provide actionable tips on how to reduce emissions.",
    },
    "Gujarati": {
        "app_title": "શાળાઓ માટે ઇકોમીટર",
        "app_header": "શાળાઓ માટે ઇકોમીટરમાં આપનું સ્વાગત છે!",
        "sidebar_title": "નેવિગેશન",
        "language_select": "ભાષા પસંદ કરો",
        "data_entry_page": "ડેટા એન્ટ્રી",
        "dashboard_page": "ડેશબોર્ડ",
        "leaderboard_page": "લીડરબોર્ડ",
        "admin_page": "એડમિન",
        "activity_type": "પ્રવૃત્તિનો પ્રકાર",
        "electricity": "વીજળી (kWh)",
        "paper": "કાગળ (શીટ્સ)",
        "plastic": "પ્લાસ્ટિક (કિલો)",
        "food_waste": "ખોરાક/કચરો (કિલો)",
        "transport": "પરિવહન (કિમી)",
        "quantity": "જથ્થો",
        "submit": "સબમિટ કરો",
        "success_message": "ડેટા સફળતાપૂર્વક સબમિટ થયો!",
        "dashboard_title": "કાર્બન ફૂટપ્રિન્ટ ડેશબોર્ડ",
        "total_emissions": "કુલ CO₂ ઉત્સર્જન",
        "emissions_by_activity": "પ્રવૃત્તિ દ્વારા ઉત્સર્જન",
        "leaderboard_title": "લીડરબોર્ડ",
        "rank": "ક્રમ",
        "school": "શાળા",
        "co2_emissions": "CO₂ ઉત્સર્જન (કિલો)",
        "admin_title": "એડમિન પેનલ",
        "verify_data": "ડેટા એન્ટ્રી ચકાસો",
        "manage_users": "વપરાશકર્તાઓનું સંચાલન કરો",
        "download_data": "ડેટા ડાઉનલોડ કરો",
        "clear_entries": "એન્ટ્રીઓ સાફ કરો",
        "add_school": "શાળા ઉમેરો",
        "remove_school": "શાળા દૂર કરો",
        "school_name": "શાળાનું નામ",
        "add": "ઉમેરો",
        "remove": "દૂર કરો",
        "clear_entries_confirmation": "શું તમે ખરેખર બધી એન્ટ્રીઓ સાફ કરવા માંગો છો? આ ક્રિયાને પૂર્વવત્ કરી શકાતી નથી.",
        "entries_cleared": "બધી એન્ટ્રીઓ સાફ થઈ ગઈ છે.",
        "school_added": "શાળા સફળતાપૂર્વક ઉમેરાઈ!",
        "school_removed": "શાળા સફળતાપૂર્વક દૂર થઈ!",
        "how_to_toggle_themes": "થીમ્સ કેવી રીતે ટૉગલ કરવી:",
        "theme_instructions_1": "ઉપરના જમણા ખૂણામાં સેટિંગ્સ મેનૂ (ત્રણ બિંદુઓ) પર ક્લિક કરો.",
        "theme_instructions_2": "'સેટિંગ્સ' પસંદ કરો.",
        "theme_instructions_3": "'થીમ' ડ્રોપડાઉનમાંથી તમારી ઇચ્છિત થીમ પસંદ કરો.",
        "how_to_update_language": "ભાષાના ટેક્સ્ટ લેબલ્સ કેવી રીતે અપડેટ કરવા:",
        "language_instructions_1": "languages.py ફાઇલ ખોલો.",
        "language_instructions_2": "LANGUAGES ડિક્શનરી શોધો.",
        "language_instructions_3": "ઇચ્છિત ભાષા માટે ટેક્સ્ટ અપડેટ કરો (દા.ત., LANGUAGES['Gujarati']['app_title'] = 'નવું શીર્ષક').",
    },
}
