LANGUAGES = {
    "English": {
        "app_title": "EcoMeter for Schools",
        "app_header": "Welcome to EcoMeter for Schools!",
        "sidebar_title": "Navigation",
        "language_select": "Select Language",
        "data_entry_page": "Data Entry",
        "dashboard_page": "Dashboard",
        "leaderboard_page": "Leaderboard",
        "admin_page": "Admin",
        "activity_type": "Activity Type",
        "electricity": "Electricity (kWh)",
        "paper": "Paper (sheets)",
        "plastic": "Plastic (kg)",
        "food_waste": "Food/Waste (kg)",
        "transport": "Transport (km)",
        "quantity": "Quantity",
        "submit": "Submit",
        "success_message": "Data submitted successfully!",
        "dashboard_title": "Carbon Footprint Dashboard",
        "total_emissions": "Total CO₂ Emissions",
        "emissions_by_activity": "Emissions by Activity",
        "emissions_by_school": "Emissions by School",
        "leaderboard_title": "Leaderboard",
        "rank": "Rank",
        "school": "School",
        "co2_emissions": "CO₂ Emissions (kg)",
        "admin_title": "Admin Panel",
        "verify_data": "Verify Data Entries",
        "manage_users": "Manage Users",
        "download_data": "Download Data",
        "clear_entries": "Clear Entries",
        "add_school": "Add School",
        "remove_school": "Remove School",
        "school_name": "School Name",
        "add": "Add",
        "remove": "Remove",
        "clear_entries_confirmation": "Are you sure you want to clear all entries? This action cannot be undone.",
        "entries_cleared": "All entries have been cleared.",
        "school_added": "School added successfully!",
        "school_removed": "School removed successfully!",
        "all_entries_cleared": "All data entries have been cleared.",
        "how_to_toggle_themes": "How to toggle themes:",
        "theme_instructions_1": "Click the settings menu (three dots) in the top right corner.",
        "theme_instructions_2": "Select 'Settings'.",
        "theme_instructions_3": "Choose your desired theme from the 'Theme' dropdown.",
        "how_to_update_language": "How to update language text labels:",
        "language_instructions_1": "Open the languages.py file.",
        "language_instructions_2": "Locate the LANGUAGES dictionary.",
        "language_instructions_3": "Update the text for the desired language (e.g., LANGUAGES['English']['app_title'] = 'New Title').",
        "dashboard_suggestions": "Dashboard Suggestions",
        "suggestion_1": "- A time-series chart to show emissions over time.",
        "suggestion_2": "- A 'Top Contributors' section to highlight the activities that contribute the most to the carbon footprint.",
        "suggestion_3": "- A 'Recommendations' section to provide actionable tips on how to reduce emissions.",
        "best_practices": "Best Practices",
        "caching_tip": "- Caching: Summaries are cached to avoid redundant API calls and improve performance.",
        "async_tip": "- Asynchronous Requests: For more complex applications, consider using asynchronous requests to avoid blocking the Streamlit app.",
        "prompts_tip": "- Clear Prompts: Provide clear and concise prompts to the LLM to get the best results.",
        "local_deployment_tip": "- Local Deployment: While this example uses an API, you can also run smaller, open-source models locally using libraries like transformers and ctransformers. However, this requires a powerful computer with a dedicated GPU.",
        "select_page": "Select a lang.",
        "reset": "Reset",
    },
    "Gujarati": {
        "app_title": "શાળાઓ માટે ઇકોમીટર",
        "app_header": "શાળાઓ માટે ઇકોમીટરમાં આપનું સ્વાગત છે!",
        "sidebar_title": "નેવિગેશન",
        "language_select": "ભાષા પસંદ કરો",
        "data_entry_page": "ડેટા એન્ટ્રી",
        "dashboard_page": "ડેશબોર્ડ",
        "leaderboard_page": "લીડરબોર્ડ",
        "admin_page": "એડમિન",
        "activity_type": "પ્રવૃત્તિનો પ્રકાર",
        "electricity": "વીજળી (kWh)",
        "paper": "કાગળ (શીટ્સ)",
        "plastic": "પ્લાસ્ટિક (કિલો)",
        "food_waste": "ખોરાક/કચરો (કિલો)",
        "transport": "પરિવહન (કિમી)",
        "quantity": "જથ્થો",
        "submit": "સબમિટ કરો",
        "success_message": "ડેટા સફળતાપૂર્વક સબમિટ થયો!",
        "dashboard_title": "કાર્બન ફૂટપ્રિન્ટ ડેશબોર્ડ",
        "total_emissions": "કુલ CO₂ ઉત્સર્જન",
        "emissions_by_activity": "પ્રવૃત્તિ દ્વારા ઉત્સર્જન",
        "emissions_by_school": "શાળા દ્વારા ઉત્સર્જન",
        "leaderboard_title": "લીડરબોર્ડ",
        "rank": "ક્રમ",
        "school": "શાળા",
        "co2_emissions": "CO₂ ઉત્સર્જન (કિલો)",
        "admin_title": "એડમિન પેનલ",
        "verify_data": "ડેટા એન્ટ્રી ચકાસો",
        "manage_users": "વપરાશકર્તાઓનું સંચાલન કરો",
        "download_data": "ડેટા ડાઉનલોડ કરો",
        "clear_entries": "એન્ટ્રીઓ સાફ કરો",
        "add_school": "શાળા ઉમેરો",
        "remove_school": "શાળા દૂર કરો",
        "school_name": "શાળાનું નામ",
        "add": "ઉમેરો",
        "remove": "દૂર કરો",
        "clear_entries_confirmation": "શું તમે ખરેખર બધી એન્ટ્રીઓ સાફ કરવા માંગો છો? આ ક્રિયાને પૂર્વવત્ કરી શકાતી નથી.",
        "entries_cleared": "બધી એન્ટ્રીઓ સાફ થઈ ગઈ છે.",
        "school_added": "શાળા સફળતાપૂર્વક ઉમેરાઈ!",
        "school_removed": "શાળા સફળતાપૂર્વક દૂર થઈ!",
        "all_entries_cleared": "બધી ડેટા એન્ટ્રીઓ સાફ થઈ ગઈ છે.",
        "theme_instructions_1": "ઉપરના જમણા ખૂણામાં સેટિંગ્સ મેનૂ (ત્રણ બિંદુઓ) પર ક્લિક કરો.",
        "theme_instructions_2": "'સેટિંગ્સ' પસંદ કરો.",
        "theme_instructions_3": "'થીમ' ડ્રોપડાઉનમાંથી તમારી ઇચ્છિત થીમ પસંદ કરો.",
        "how_to_update_language": "ભાષાના ટેક્સ્ટ લેબલ્સ કેવી રીતે અપડેટ કરવા:",
        "language_instructions_1": "languages.py ફાઇલ ખોલો.",
        "language_instructions_2": "LANGUAGES ડિક્શનરી શોધો.",
        "language_instructions_3": "ઇચ્છિત ભાષા માટે ટેક્સ્ટ અપડેટ કરો (દા.ત., LANGUAGES['Gujarati']['app_title'] = 'નવું શીર્ષક').",
        "dashboard_suggestions": "ડેશબોર્ડ સૂચનો",
        "suggestion_1": "- સમય જતાં ઉત્સર્જન બતાવવા માટે સમય-શ્રેણીનો ચાર્ટ.",
        "suggestion_2": "- કાર્બન ફૂટપ્રિન્ટમાં સૌથી વધુ ફાળો આપતી પ્રવૃત્તિઓને હાઇલાઇટ કરવા માટે 'ટોચના ફાળો આપનારા' વિભાગ.",
        "suggestion_3": "- ઉત્સર્જન ઘટાડવા માટે કાર્યક્ષમ ટિપ્સ પ્રદાન કરવા માટે 'ભલામણો' વિભાગ.",
        "best_practices": "શ્રેષ્ઠ પ્રયાસો",
        "caching_tip": "- કેશીંગ: પુનરાવર્તિત API કૉલ્સને ટાળવા અને પ્રદર્શન સુધારવા માટે સારાંશ કેશ કરવામાં આવે છે.",
        "async_tip": "- અસુમેળ વિનંતીઓ: વધુ જટિલ એપ્લિકેશનો માટે, સ્ટ્રીમલિટ એપ્લિકેશનને અવરોધિત કરવાનું ટાળવા માટે અસુમેળ વિનંતીઓનો ઉપયોગ કરવાનું વિચારો.",
        "prompts_tip": "- સ્પષ્ટ પ્રોમ્પ્ટ્સ: શ્રેષ્ઠ પરિણામો મેળવવા માટે LLM ને સ્પષ્ટ અને સંક્ષિપ્ત પ્રોમ્પ્ટ્સ પ્રદાન કરો.",
        "local_deployment_tip": "- સ્થાનિક જમાવટ: જ્યારે આ ઉદાહરણ API નો ઉપયોગ કરે છે, ત્યારે તમે ટ્રાન્સફોર્મર્સ અને ctransformers જેવી લાઇબ્રેરીઓનો ઉપયોગ કરીને સ્થાનિક રીતે નાના, ઓપન-સોર્સ મોડલ્સ પણ ચલાવી શકો છો. જો કે, આ માટે સમર્પિત GPU સાથે શક્તિશાળી કમ્પ્યુટરની જરૂર છે.",
        "select_page": "એક ભાષા પસંદ કરો.",
        "reset": "રીસેટ",
    },
}
